(in-package :lang.cypher)


(defvar *functions* '(
                      :abs
                      :acos
                      :all
                      :any
                      :asin
                      :atan
                      :atan2
                      :avg
                      :ceil
                      :coalesce
                      :collect
                      :cos
                      :cot
                      :count
                      :date
                      :datetime
                      :degrees
                      :distance
                      :duration
                      :e
                      :end-node
                      :exists
                      :exp
                      :extract
                      :filter
                      :floor
                      :haversin
                      :head
                      :id
                      :keys
                      :l-trim
                      :labels
                      :last
                      :left
                      :length
                      :localdatetime
                      :localtime
                      :log
                      :log10
                      :max
                      :min
                      :nodes
                      :none
                      :percentile-cont
                      :percentile-disc
                      :pi
                      :point
                      :properties
                      :r-trim
                      :radians
                      :rand
                      :random-uuid
                      :range
                      :reduce
                      :relationships
                      :replace
                      :reverse
                      :right
                      :round
                      :sign
                      :sin
                      :single
                      :size
                      :split
                      :sqrt
                      :st-dev
                      :st-dev-p
                      :start-Node
                      :substring
                      :sum
                      :tail
                      :tan
                      :time
                      :timestamp
                      :to-boolean
                      :to-float
                      :to-integer
                      :to-lower
                      :to-string
                      :to-upper
                      :trim
                      :type
                      ))
